### PR TITLE
Solve a problem with the new sdk on iOS 11 that causes an extra space…

### LINKED ISSUE #630: iOS 11 offset in tableView
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
With the brand new iOS 11,  there appears an offset on the table view of the SlackTextViewController.

#### Reproducible in:
* [x] This is reproducible in the sample project.
SlackTextViewController version: 1.9.5
iOS version(s): iOS 11
Device(s): Anyone (I attach an screen shot of iPhone 7 Plus)

#### Steps to reproduce:

1. Download the sample project.
2. Run it with the iOS 11 simulator and iOS 10.3 simulator (using Xcode 9)

### Expected result:
The table should appear without any content offset (iPhone 7 Plus, iOS 10.3.1)

iPhone 7 Plus iOS 10.3.1

### Actual result:
The table has offset (iPhone 7 Plus, iOS 11)

iPhone 7 Plus iOS 11

Thank you for your help!

Josep

### PR DESCRIPTION
**Pull request by josepbordesjove**
… in the bottom due to automatic content inset adjustment.

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CODE_OF_CONDUCT.md).
* [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferrably).
* [x] I've written tests to cover the new code and functionality included in this PR.
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).

### CODE REVIEW

**Comment by josepbordesjove** [comment]
@dzenbot No... the problem here is because of a new property apple add to scrollViews, and it only affects iOS 11.

captura_de_pantalla_2017-09-28_a_les_17 31 39_720

**Comment by kushak** [comment]
Update tag -> 1.9.6  pls

**Comment by josepbordesjove** [comment]
@kushak Today I'll update the tag!

**Comment by josepbordesjove** [comment]
@kushak I added the tag 1.9.6 and @cornr I changed the place where the insets were adjusted, thank you.

File: Source/SLKTextViewController.m [hunk 1]
```diff
@@ -186,6 +186,11 @@ - (void)viewWillAppear:(BOOL)animated
 {
     [super viewWillAppear:animated];
     
+    // Deactivate automatic scrollView adjustment
```
Comment (cornr) [inline Source/SLKTextViewController.m]: Remove this code because it duplicates the code in the tableView initialization.

**Comment by josepbordesjove** [comment]
@cornr Sorry, I forgot about it... Solved!

**Comment by yarodevuci** [comment]
Where do we put that??
